// Organic SEO Services page ke FAQs (page par bhi dikhte hain aur Google FAQ schema mein bhi jaate hain)
export const FAQS: { q: string; a: string }[] = [
  { q: "What are organic SEO services?", a: "Organic SEO services improve your website so it ranks in unpaid search results on Google, Bing and AI answer engines. They include technical SEO, keyword research, content, on-page optimization and link building." },
  { q: "How is organic SEO different from paid search?", a: "With paid search you pay for every click and traffic stops when the budget stops. Organic SEO earns rankings that keep sending traffic without a cost per click, so the return grows over time." },
  { q: "How long does organic SEO take to work?", a: "Most sites see clear movement in 3 to 6 months and strong growth in 6 to 12 months. New websites and competitive industries take longer. We share a realistic timeline after the free audit." },
  { q: "How much do organic SEO services cost?", a: "Pricing depends on your goals, competition and how much content and link building you need. After a free audit you get a fixed monthly quote, with no setup fees and no long-term contract." },
  { q: "Do you guarantee first page rankings?", a: "No honest organic SEO company can guarantee rankings, because Google controls them. We guarantee a clear plan, work shipped every month and transparent reporting on traffic and leads." },
  { q: "What do your organic SEO specialists do each month?", a: "They ship technical fixes, publish or improve pages, earn links, update local listings and report on rankings, traffic, leads and AI visibility, following a plan we agree with you." },
  { q: "Do you offer organic SEO services for small business?", a: "Yes. Small businesses are a large part of our work. We focus on the few keywords and pages that bring calls and customers, not on vanity traffic." },
  { q: "Are you an organic SEO company in India?", a: "Yes. CodedSEO is an organic SEO services company in India, based in Sector 74, Mohali, Punjab, and serves clients in India, the USA, the UK, Canada and Australia. You get senior SEO experience at a fair price, with calls in your time zone." },
  { q: "Will organic SEO help me show up in AI Overviews and ChatGPT?", a: "Yes, it is built into our plan. Clear answers, schema, consistent brand facts and trusted content make your site more likely to be cited by AI Overviews, ChatGPT and Perplexity." },
  { q: "Do I need to sign a long-term contract?", a: "No. We work month to month. 98% of our clients stay because of results, not paperwork." },
  { q: "How do I choose the best organic SEO company?", a: "Whichever organic search engine optimization company you pick, look for real case studies, white-hat link building, clear reporting tied to leads, experience with AI search and honest timelines. Avoid anyone who guarantees rankings or hides what they do." },
];

export const STEPS: { tab: string; when: string; title: string; text: string; items: string[] }[] = [
  {"tab": "Audit", "when": "Week 1", "title": "Find what is holding you back", "text": "A full technical, content and backlink audit, plus a look at how leads arrive today.", "items": ["Crawl, indexing and Core Web Vitals review", "Content quality and cannibalization check", "Backlink profile and toxic link review", "Conversion and tracking check in GA4"]},
  {"tab": "Research", "when": "Week 1 to 2", "title": "Learn how your buyers search", "text": "Keyword and competitor research focused on intent, so we chase searches that turn into revenue.", "items": ["Buyer-intent keyword research", "Competitor gap analysis", "Search intent and SERP feature review", "AI answer and People Also Ask research"]},
  {"tab": "Strategy", "when": "Week 2 to 3", "title": "Build a 90-day plan you can read", "text": "A prioritized roadmap: what we fix, what we create and which links we go after, in order of impact.", "items": ["Keyword-to-page map", "Technical fix priority list", "Content calendar", "Link building targets"]},
  {"tab": "Optimize", "when": "Month 1 to 3", "title": "Fix and improve what you have", "text": "Most sites already own pages that could rank. We fix those first for the fastest wins.", "items": ["Technical fixes shipped", "On-page optimization of priority pages", "Schema markup added", "Internal links rebuilt"]},
  {"tab": "Build authority", "when": "Month 2 onward", "title": "Earn trust with content and links", "text": "New content that answers real questions, and links from websites Google already trusts.", "items": ["New pages and guides published", "White-hat outreach and digital PR", "Local citations and reviews (local clients)", "Brand mentions for AI search"]},
  {"tab": "Report and refine", "when": "Every month", "title": "Measure, learn and double down", "text": "Monthly reporting tied to leads, then a plan update based on what is working.", "items": ["Monthly report and strategy call", "Rank, traffic and lead tracking", "Refresh of slipping pages", "Next month's priorities agreed"]},
];
