// SEO Outsourcing India page ke FAQs (page par bhi dikhte hain aur Google FAQ schema mein bhi jaate hain)
export const FAQS: { q: string; a: string }[] = [
  { q: "What is SEO outsourcing?", a: "SEO outsourcing means handing some or all of your SEO work to an outside team instead of hiring in-house. Agencies use an SEO outsourcing agency to deliver client campaigns under their own brand, and businesses use one to get a full SEO team for less than one salary. You will also see it called SEO outsource India, SEO India outsourcing or India outsource SEO; they all mean the same thing." },
  { q: "Why outsource SEO to India instead of hiring in-house?", a: "Cost and speed. A three-person in-house team in the US can cost $15,000 or more a month before tools. Outsourcing SEO to India gives you strategists, writers and link builders from day one, for one flat monthly fee per client, with no recruiting or training time." },
  { q: "How does your white label SEO program work?", a: "You sell SEO to your client at your price. We do the audits, strategy, content, links and reporting, and deliver everything with your logo. Your client talks only to you, and we sign an NDA and a non-solicit before kickoff." },
  { q: "Will my clients know you exist?", a: "No. Reports, proposals and emails are fully unbranded or carry your brand. If you want us on a client call, we join as your SEO team." },
  { q: "How is SEO outsourcing India pricing decided?", a: "Pricing depends on how many clients you send, the number of keywords and how much content and link building each needs. After a free audit you get a fixed monthly quote per client, with volume pricing for 10 or more clients, no setup fees and no long-term contracts." },
  { q: "How long before my clients see results?", a: "Most campaigns show clear movement in 3 to 6 months. Local SEO and long-tail keywords often move sooner, while competitive national terms take longer. We share a realistic timeline in the proposal before you commit." },
  { q: "Do you handle AI SEO and GEO?", a: "Yes. We optimize content, schema and entity signals so clients can be cited in Google AI Overviews, ChatGPT, Gemini and Perplexity, and we track AI visibility in the monthly report. Our guide on what AI SEO is explains the approach." },
  { q: "What reports will I receive and how often?", a: "Weekly ranking snapshots and a monthly performance report covering rankings, organic traffic, leads, links earned, technical fixes and AI visibility, all white labeled for your agency." },
  { q: "Is outsourcing SEO India work safe for my client data?", a: "Yes. We sign an NDA before kickoff, ask only for the access a task needs, keep logins in an encrypted password manager and remove access when a project ends. Your client relationships and data stay yours." },
  { q: "How do you handle time zones and communication?", a: "You get one project manager, a shared task board and your choice of email, Slack or Google Meet. We keep a daily overlap with US and UK hours for calls, and work moves forward overnight while you are offline." },
  { q: "How do I choose the right SEO outsourcing partner in India?", a: "Check for real case studies, clear reporting, white label support, white-hat link building and experience with AI search. Ask for a sample report and start with one client before moving your whole book of business." },
];
